name: kimofit
description: "Persomal Trainer App"

publish_to: 'none' 

version: 1.0.8+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # State management
  flutter_bloc: ^8.1.5
  # For Dependency Injection
  get_it: ^7.7.0
  # HTTP networking package, for making REST API calls
  dio: ^5.4.3+1
  # For logging HTTP requests and responses in a pretty format
  pretty_dio_logger: ^1.3.1
  # Customize Flutter splash screen
  flutter_native_splash: ^2.4.0
  # For App Lancher Icon
  flutter_launcher_icons: ^0.13.1
  # For Responsive UI
  flutter_screenutil: ^5.9.1
  # For Translation and Localization
  intl: ^0.19.0
  flutter_localizations:
        sdk: flutter
  # For Saving Data Locally in cache
  shared_preferences: ^2.2.3
  # For animation Images
  lottie: ^3.1.2
  # For International Phone Field
  intl_phone_field: ^3.1.0
  # For Get Device Info (unique id)
  device_info_plus: ^10.1.0
  # For Error Handling
  dartz: ^0.10.1
  # Firebase Core, enabling connecting to multiple Firebase apps
  firebase_core: ^3.0.0
  # provides API to store data in secure storage
  flutter_secure_storage: ^9.2.2
  # Display progress widgets based on percentage
  percent_indicator: ^4.2.3
  # Carousel slider widget, support infinite scroll 
  carousel_slider: ^4.2.1
  # Plugin for launching a URL
  url_launcher: ^6.3.0
  # Provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # Create and apply corner badges ( Free and Pro )
  rotated_corner_decoration: ^2.1.0+1
  # Font Awesome Icon pack available as Flutter Icons
  font_awesome_flutter: ^10.7.0
  # Load and cache network images
  cached_network_image: ^3.3.1
  # Custom refresh indicator with some cool animations
  liquid_pull_to_refresh: ^3.0.1
  # Provides a collection of Flutter grids layouts
  flutter_staggered_grid_view: ^0.7.0
  # Flutter plugin to enable, disable or toggle screenshot and screen recording
  no_screenshot: ^0.0.1+6
  # Customizable animated page indicator with a set of built-in effects
  smooth_page_indicator: ^1.1.0


flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/icon/app_icon.png"
  min_sdk_android: 21 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  intl: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/bg/
    - assets/images/logo/
    - assets/animation/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada-Regular.ttf

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
  field_prefix:
