default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:238941174298:android:d565153bc67d6be83cafa3",
        firebase_cli_token: "1//03QtIRuYRuosSCgYIARAAGAMSNgF-L9IrUFk1tpPWAPo1D4yKNxLXbmddB0YY8SuVmgx0FPBE3A8xhOgn8i8wfbIo69qMBXcR4Q",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        groups: "testing-group",
        release_notes: "First release of the app using fastlane for distribution!"
  )
  end
end
